### ISSUE TITLE
Error handling problem when using local database

### ISSUE THREAD

**Issue by penberg** [libsql/libsql-node-sqlite3#4]
Dan Kochetov from Drizzle team writes:

> Seems like when I'm using a local db and there's an error returned from sqlite3, the process immediately exits, even if I wrap the query in a try-catch block.

**Comment by honzasp** [comment]
I also noticed that `node-sqlite3` sometimes aborts when misused. I think that the problem lies in the original library, not in our wrapper (which does basically nothing when a local db is used).

**Comment by honzasp** [comment]
Closing, because this is not caused by our library.
